[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Thoralf Müller <thoralf.mueller@iota.org", "Antony Dikov <antoni.dikov@iota.org>", "Bing-Yang Lin <bingyang.lin@iota.org>", "Lucas Nogueira <lucas.nogueira@iota.org>", "Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[dependencies]
bee-rest-api = { git = "https://github.com/iotaledger/bee.git", rev = "e8cafb6591ec0c29f80705ae51fb8cb890fa98b0", default-features = false }
bee-message = { git = "https://github.com/iotaledger/bee.git", rev = "e8cafb6591ec0c29f80705ae51fb8cb890fa98b0", default-features = false }
bee-pow = { git = "https://github.com/iotaledger/bee.git", rev = "e8cafb6591ec0c29f80705ae51fb8cb890fa98b0", default-features = false  }
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", rev = "c42171ff33c80cc2efb183e244dc79b7f58d9ac4" }
iota-crypto = { git = "https://github.com/iotaledger/crypto.rs.git", rev = "b849861b86c3f7357b7477de4253b7352b363627", features = ["std", "blake2b", "ed25519", "random", "slip10"]}
ureq = { version = "2.0", features = ["json"], optional = true }
reqwest = { version = "0.11", features = ["json", "rustls-tls", "blocking"], default-features = false, optional = true }
url = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
tokio = { version = "1.1", features = ["macros", "sync", "rt-multi-thread", "rt"] }
thiserror = "1.0"
num_cpus = "1.13"
rusqlite = { version = "0.24", features = ["bundled"], optional = true }
async-trait = "0.1"
log= "0.4"

# MQTT
rumqttc = { version = "0.5", optional = true }
regex = { version = "1.4", optional = true }
once_cell = { version = "1.5", optional = true }
futures = { version = "0.3", optional = true }

[features]
default = ["async"]
sync = ["ureq"]
async = ["reqwest"]
mqtt = ["rumqttc", "regex", "once_cell", "futures"]
storage = ["rusqlite", "once_cell"]
