[book]
title = "Chrysalis Documentation"
authors = ["Sebastian Heusser <sebastian.heusser@iota.org>"]
language = "en"
multilingual = false
src = "docs"

[output.html]
theme = "theme"
additional-css = ["./theme/css/custom.css", "./theme/css/custom/header.css"]
default-theme = "iota"
git-repository-url = "https://github.com/iotaledger/chrysalis-docs"
git-repository-icon = "fa-github"
