[book]
authors = ["Thoralf Müller <thoralf.mueller@iota.org",  "Sebastian Heusser <sebastian.heusser@iota.org>", "Antony Dikov <antoni.dikov@iota.org>", "Bing-Yang Lin <bingyang.lin@iota.org>"]
language = "en"
multilingual = false
src = "./docs"
title = "IOTA Client Library"

[output.html]
default-theme = "IOTA"
git-repository-url = "https://github.com/iotaledger/iota.rs"
git-repository-icon = "fa-github"
theme = "./docs/theme"
additional-css = ["./docs/theme/css/custom/header.css"]

[output.html.playpen]
editable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2